AllCops:
  Exclude:
    - build/**/*
    - docs/**/*
    - backend/app/converters/ead_converter.rb

Metrics:
  Enabled: false

Style/Alias:
  AutoCorrect: false

Style/BlockDelimiters:
  AutoCorrect: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  AutoCorrect: false

Style/PreferredHashMethods:
  AutoCorrect: false

Style/SymbolArray:
  AutoCorrect: false

Style/UnneededInterpolation:
  AutoCorrect: false

Style/WordArray:
  AutoCorrect: false
